### ISSUE TITLE
Configure credentials for the container

### ISSUE THREAD

**Issue by dee-kryvenko** [plumber-cd/runtainer#23]
Need an ability to securely pass credentials to the container not otherwise available on the host.

Should be able to use k8s secret to inject env variables and mount files.

**Comment by dee-kryvenko** [comment]
In the `.runtainer.yaml` - should be able to specify:

```yaml
secrets:
  env:
    - foo
  volumes:
    - bar
```

Also from command line:

```bash
runtainer --secret-env foo --secret-volume bar alpine sh
```

Resulting pod will be generated as follows:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: runtainer
spec:
  volumes:
    - name: secret-bar
      secret:
        secretName: bar
        optional: true
  containers:
    - name: runtainer
      image: alpine
      envFrom:
        - secretRef:
            name: foo
            optional: true
      volumeMounts:
        - name: secret-bar
          mountPath: "/rt-secrets/bar"
          readOnly: true
```
